### PR TITLE
Simplify the test workflow by using job level defaults

### PR DESCRIPTION
**Pull request by chrispat**
A little bit of a wonky work around but you can use the `matrix` context in the defaults for the job which does simplify the test workflow a bit.

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks, this is an improvement!! It'd still be great to do it without the defaults, of course :-)

**Comment by ljharb** [comment]
@chrispat hmm, looks like dash, ksh, and zsh aren't valid shell options :-/ https://github.com/ljharb/nvm/runs/1658993703?check_suite_focus=true

**Comment by chrispat** [comment]
You are going to need to update that to be the full format string in the case where it is not one of the built-in options sorry I should have made the example more complete https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#custom-shell.


Error: Invalid shell option. Shell must be a valid built-in (bash, sh, cmd, powershell, pwsh) or a format string containing '{0}'

**Comment by ljharb** [comment]
ok - what would the string value be tho, if those shells aren't already installed?

**Comment by chrispat** [comment]
It depends on the shell but it is in the general format of `executable [options] {0} [options]` where the `{0}` is replaced by the path to the script file that we generate.

From the docs https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#custom-shell
You can set the shell value to a template string using command […options] {0} [..more_options]. GitHub interprets the first whitespace-delimited word of the string as the command, and inserts the file name for the temporary script at {0}..

**Comment by ljharb** [comment]
The docs (and your comment) are unclear to me. I think what I'd need to see is what the "special" shell options would be, if done as a template string.

**Comment by chrispat** [comment]
The options are completely dependent on the shell you want to run and if you need any special options for that shell.  It may be the case the `/bin/csh {0}` is sufficient for the `csh` shell.  In the case of PowerShell core we run `pwsh -File {0}`.  I just don't know those other shells but expect given they are `sh` style shells it should be similar to what we do for bash https://github.com/actions/runner/blob/e808190dd27a77fa79ce6c2890ef79ace26af500/src/Runner.Worker/Handlers/ScriptHandlerHelpers.cs#L14.

**Comment by ljharb** [comment]
ah ok, i'll try that, thanks

**Pull request merged**
